version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"   # Expose port for Streamlit
    restart: always   # Automatically restart the container if it crashes
